// Generated by gencpp from file kinect_anywhere/BodyFrame.msg
// DO NOT EDIT!


#ifndef KINECT_ANYWHERE_MESSAGE_BODYFRAME_H
#define KINECT_ANYWHERE_MESSAGE_BODYFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kinect_anywhere/Body.h>

namespace kinect_anywhere
{
template <class ContainerAllocator>
struct BodyFrame_
{
  typedef BodyFrame_<ContainerAllocator> Type;

  BodyFrame_()
    : bodies()  {
    }
  BodyFrame_(const ContainerAllocator& _alloc)
    : bodies(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::kinect_anywhere::Body_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::kinect_anywhere::Body_<ContainerAllocator> >::other >  _bodies_type;
  _bodies_type bodies;




  typedef boost::shared_ptr< ::kinect_anywhere::BodyFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_anywhere::BodyFrame_<ContainerAllocator> const> ConstPtr;

}; // struct BodyFrame_

typedef ::kinect_anywhere::BodyFrame_<std::allocator<void> > BodyFrame;

typedef boost::shared_ptr< ::kinect_anywhere::BodyFrame > BodyFramePtr;
typedef boost::shared_ptr< ::kinect_anywhere::BodyFrame const> BodyFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect_anywhere::BodyFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect_anywhere

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'kinect_anywhere': ['/home/baxter/Desktop/PierreROS/src/kinect_anywhere/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect_anywhere::BodyFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_anywhere::BodyFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_anywhere::BodyFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8ca6cd86f661b94d3cea79f1dad0380";
  }

  static const char* value(const ::kinect_anywhere::BodyFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8ca6cd86f661b94ULL;
  static const uint64_t static_value2 = 0xd3cea79f1dad0380ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect_anywhere/BodyFrame";
  }

  static const char* value(const ::kinect_anywhere::BodyFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Body[] bodies\n\
\n\
================================================================================\n\
MSG: kinect_anywhere/Body\n\
Header header\n\
uint64 trackingId\n\
JointPositionAndState[] jointPositions\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: kinect_anywhere/JointPositionAndState\n\
int32 trackingState\n\
geometry_msgs/Point position\n\
int32 jointType\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::kinect_anywhere::BodyFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bodies);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BodyFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_anywhere::BodyFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect_anywhere::BodyFrame_<ContainerAllocator>& v)
  {
    s << indent << "bodies[]" << std::endl;
    for (size_t i = 0; i < v.bodies.size(); ++i)
    {
      s << indent << "  bodies[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kinect_anywhere::Body_<ContainerAllocator> >::stream(s, indent + "    ", v.bodies[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_ANYWHERE_MESSAGE_BODYFRAME_H
